{
  description = "Nebelung — Catppuccin Mocha with the blue stripped (theme builder)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    # whiskers (the Catppuccin templating CLI) is not in nixpkgs; it ships from
    # the catppuccin flake. This is the same input the consuming nix config
    # already has, so `follows` there keeps a single whiskers in the closure.
    catppuccin.url = "github:catppuccin/nix";
    # NOTE: the catppuccin userstyles export (import.json) is VENDORED at
    # vendor/catppuccin-userstyles-export.json instead of fetched. Upstream's
    # "all-userstyles-export" release asset is a ROLLING URL whose narHash drifts
    # whenever catppuccin republishes it — which silently broke every consumer's
    # CI (local builds pass from cache; fresh CI fetches don't). Vendoring pins it
    # for real. Re-vendor by hand (re-download that URL) to pick up a newer export.
  };

  outputs =
    { self, nixpkgs, catppuccin }:
    let
      systems = [ "aarch64-darwin" "x86_64-darwin" "aarch64-linux" "x86_64-linux" ];
      forSystems = nixpkgs.lib.genAttrs systems;

      # Which variants exist, from which catppuccin flavor, into which subdir of
      # the themes package — generated by scripts/generate-palette.mjs from its
      # VARIANTS table, so this flake can't disagree with what build.sh rendered.
      variantManifest = builtins.fromJSON (builtins.readFile ./palette/variants.json);
      readHexMap =
        name:
        builtins.mapAttrs (_: v: "#${v}") (
          builtins.fromJSON (builtins.readFile (./palette + "/${name}.hex.json"))
        );
    in
    {
      # The Nebelung palette as a plain name -> "#hex" attrset, read from the
      # committed hex map. Nix-native consumers that can't take a rendered file
      # (e.g. a starship `[palettes.*]` table) inject this directly — no
      # duplication, the JSON stays the single source of truth.
      palette = readHexMap "nebelung";

      # Every variant, by name, in the same name -> "#hex" shape. `palette`
      # above stays the default one so existing consumers are untouched; a
      # consumer that wants to follow a flavor/contrast setting reads from here.
      # Rendered port files live under the matching subdir of the themes package
      # (dist/ for the default, dist/<variants.<name>.dir>/ for the rest).
      palettes = builtins.mapAttrs (name: _: readHexMap name) variantManifest;

      # The manifest itself: name -> { flavor, dir }. `flavor` is the catppuccin
      # flavor the variant was rendered as, which a consumer needs in order to
      # build the flavor-named paths whiskers emits (catppuccin-latte.conf vs
      # catppuccin-mocha.conf, zen/themes/Latte/ vs /Mocha/). `dir` is its
      # subdirectory inside the themes package, "" for the default.
      variants = variantManifest;

      # Per-port install metadata: name -> { title, path, platform, dest,
      # install, select, tier, howto, ... }. ports.conf says which ports get RENDERED; this says
      # what installing one actually takes, in a shape a config manager can act
      # on instead of a paragraph a human has to read. `tier` is what a consumer
      # branches on:
      #   auto     — a rebuild can drop the file and make it active, end to end
      #   activate — same file drop, but the "which theme" setting lives in a
      #              file the app rewrites at runtime, so it needs an idempotent
      #              activation-time patch rather than a symlink
      #   manual   — the app has no file interface for selecting a theme; the
      #              drop can be automated, the selection can't. Surface these to
      #              the user instead of pretending they're wired.
      # `platform` (["darwin"] / ["linux"] / both) is the other filter a consumer
      # wants first: several ports are Linux-only tools that are `auto` but have
      # nothing to wire on a Mac.
      # docs/ports.md is generated from this file (scripts/gen-ports-doc.mjs) and
      # a test asserts each stored tier matches the select/install rule, so the
      # value read here can't drift from the rule that defines it.
      ports = builtins.fromJSON (builtins.readFile ./ports.meta.json);

      # `nix flake check` runs these — the same palette unit tests + shellcheck
      # that CI's `unit` job runs, so local check == CI without pushing.
      checks = forSystems (
        system:
        let
          pkgs = nixpkgs.legacyPackages.${system};
        in
        {
          palette-tests = pkgs.runCommand "nebelung-palette-tests" {
            nativeBuildInputs = [ pkgs.nodejs ];
          } ''
            cd ${self}
            node --test
            touch $out
          '';
          shellcheck = pkgs.runCommand "nebelung-shellcheck" {
            nativeBuildInputs = [ pkgs.shellcheck ];
          } ''
            shellcheck ${./build.sh}
            touch $out
          '';
        }
      );

      packages = forSystems (
        system:
        let
          pkgs = nixpkgs.legacyPackages.${system};
          whiskers = catppuccin.packages.${system}.whiskers;

          nebelung-themes = pkgs.stdenv.mkDerivation {
            pname = "nebelung-themes";
            version = "1.0.0";
            src = ./.;

            # node -> regenerate the palette + emit the vscode snippet;
            # whiskers -> render every port template. Both must be on PATH;
            # find/sed/cut/paste/xargs come from stdenv.
            nativeBuildInputs = [ pkgs.nodejs whiskers ];

            # No network, no npm deps (scripts use only Node built-ins).
            buildPhase = ''
              runHook preBuild
              export CATPPUCCIN_USERSTYLES_EXPORT="$PWD/vendor/catppuccin-userstyles-export.json"
              bash build.sh
              runHook postBuild
            '';

            # dist/<port>/... mirrors the layout home-manager sources from;
            # previews + palette JSON tag along for reference (one preview per
            # variant, and variants.json so the tree describes its own layout).
            # ports.meta.json rides along for the same reason: the tree then
            # describes how to INSTALL what's in it, not just what's in it.
            installPhase = ''
              runHook preInstall
              mkdir -p "$out/preview"
              cp -R dist/. "$out/"
              cp preview/*.html "$out/preview/"
              cp palette/*.json "$out/"
              cp ports.meta.json "$out/"
              runHook postInstall
            '';
          };
        in
        {
          default = nebelung-themes;
          nebelung-themes = nebelung-themes;
        }
      );
    };
}
